services:
  app-java:
    build: .
    environment: []
    ports:
    - 8080:8080
    volumes:
    - ./:/app
  app-kotlin:
    build: .
    environment: []
    ports:
    - 8080:8080
    volumes:
    - ./:/app
version: '3.8'
