package app.what.foundation.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val brownLightScheme by lazy {
    lightColorScheme(
        primary = Color(0xFF895120),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDCC4),
        onPrimaryContainer = Color(0xFF6D3A09),
        secondary = Color(0xFF745945),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFDCC4),
        onSecondaryContainer = Color(0xFF5B412F),
        tertiary = Color(0xFF5D6136),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFE3E7AF),
        onTertiaryContainer = Color(0xFF464A20),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        background = Color(0xFFFFF8F5),
        onBackground = Color(0xFF221A14),
        surface = Color(0xFFFFF8F5),
        onSurface = Color(0xFF221A14),
        surfaceVariant = Color(0xFFF3DFD2),
        onSurfaceVariant = Color(0xFF52443B),
        outline = Color(0xFF84746A),
        outlineVariant = Color(0xFFD6C3B7),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF382F28),
        inverseOnSurface = Color(0xFFFEEEE4),
        inversePrimary = Color(0xFFFFB780),
        surfaceDim = Color(0xFFE7D7CE),
        surfaceBright = Color(0xFFFFF8F5),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF1E9),
        surfaceContainer = Color(0xFFFBEBE1),
        surfaceContainerHigh = Color(0xFFF5E5DC),
        surfaceContainerHighest = Color(0xFFF0DFD6),
    )
}

internal val brownDarkScheme by lazy {
    darkColorScheme(
        primary = Color(0xFFFFB780),
        onPrimary = Color(0xFF4E2600),
        primaryContainer = Color(0xFF6D3A09),
        onPrimaryContainer = Color(0xFFFFDCC4),
        secondary = Color(0xFFE4BFA7),
        onSecondary = Color(0xFF422B1A),
        secondaryContainer = Color(0xFF5B412F),
        onSecondaryContainer = Color(0xFFFFDCC4),
        tertiary = Color(0xFFC6CA95),
        onTertiary = Color(0xFF2F330C),
        tertiaryContainer = Color(0xFF464A20),
        onTertiaryContainer = Color(0xFFE3E7AF),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF19120D),
        onBackground = Color(0xFFF0DFD6),
        surface = Color(0xFF19120D),
        onSurface = Color(0xFFF0DFD6),
        surfaceVariant = Color(0xFF52443B),
        onSurfaceVariant = Color(0xFFD6C3B7),
        outline = Color(0xFF9F8D82),
        outlineVariant = Color(0xFF52443B),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFF0DFD6),
        inverseOnSurface = Color(0xFF382F28),
        inversePrimary = Color(0xFF895120),
        surfaceDim = Color(0xFF19120D),
        surfaceBright = Color(0xFF413731),
        surfaceContainerLowest = Color(0xFF140D08),
        surfaceContainerLow = Color(0xFF221A14),
        surfaceContainer = Color(0xFF261E18),
        surfaceContainerHigh = Color(0xFF312822),
        surfaceContainerHighest = Color(0xFF3C332D)
    )
}