package app.what.foundation.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val greenLightScheme by lazy {
    lightColorScheme(
        primary = Color(0xFF446732),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFC5EFAB),
        onPrimaryContainer = Color(0xFF2D4F1C),
        secondary = Color(0xFF55624C),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD9E7CB),
        onSecondaryContainer = Color(0xFF3E4A35),
        tertiary = Color(0xFF386666),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFBBEBEC),
        onTertiaryContainer = Color(0xFF1E4E4E),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        background = Color(0xFFF8FAF0),
        onBackground = Color(0xFF191D16),
        surface = Color(0xFFF8FAF0),
        onSurface = Color(0xFF191D16),
        surfaceVariant = Color(0xFFE0E4D7),
        onSurfaceVariant = Color(0xFF43483E),
        outline = Color(0xFF74796D),
        outlineVariant = Color(0xFFC3C8BB),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF2E312B),
        inverseOnSurface = Color(0xFFF0F2E7),
        inversePrimary = Color(0xFFAAD291),
        surfaceDim = Color(0xFFD9DBD1),
        surfaceBright = Color(0xFFF8FAF0),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF2F5EA),
        surfaceContainer = Color(0xFFEDEFE5),
        surfaceContainerHigh = Color(0xFFE7E9DF),
        surfaceContainerHighest = Color(0xFFE1E4D9),
    )
}

internal val greenDarkScheme by lazy {
    darkColorScheme(
        primary = Color(0xFFAAD291),
        onPrimary = Color(0xFF173807),
        primaryContainer = Color(0xFF2D4F1C),
        onPrimaryContainer = Color(0xFFC5EFAB),
        secondary = Color(0xFFBDCBB0),
        onSecondary = Color(0xFF283420),
        secondaryContainer = Color(0xFF3E4A35),
        onSecondaryContainer = Color(0xFFD9E7CB),
        tertiary = Color(0xFFA0CFCF),
        onTertiary = Color(0xFF003738),
        tertiaryContainer = Color(0xFF1E4E4E),
        onTertiaryContainer = Color(0xFFBBEBEC),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF11140E),
        onBackground = Color(0xFFE1E4D9),
        surface = Color(0xFF11140E),
        onSurface = Color(0xFFE1E4D9),
        surfaceVariant = Color(0xFF43483E),
        onSurfaceVariant = Color(0xFFC3C8BB),
        outline = Color(0xFF8D9286),
        outlineVariant = Color(0xFF43483E),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFE1E4D9),
        inverseOnSurface = Color(0xFF2E312B),
        inversePrimary = Color(0xFF446732),
        surfaceDim = Color(0xFF11140E),
        surfaceBright = Color(0xFF373A33),
        surfaceContainerLowest = Color(0xFF0C0F09),
        surfaceContainerLow = Color(0xFF191D16),
        surfaceContainer = Color(0xFF1D211A),
        surfaceContainerHigh = Color(0xFF282B24),
        surfaceContainerHighest = Color(0xFF32362F)
    )
}